TRUNCATE TABLE Author RESTART IDENTITY CASCADE;
TRUNCATE TABLE Address RESTART IDENTITY CASCADE;
TRUNCATE TABLE Author_Phone RESTART IDENTITY CASCADE;
TRUNCATE TABLE Author_Email RESTART IDENTITY CASCADE;