-- ALTER SEQUENCE PUBLIC.HIBERNATE_SEQUENCE RESTART WITH 100;

TRUNCATE TABLE Author RESTART IDENTITY CASCADE ;
TRUNCATE TABLE Announcement RESTART IDENTITY CASCADE ;
TRUNCATE TABLE Rubric RESTART IDENTITY CASCADE ;




